# Generated by Django 3.1.1 on 2020-10-02 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0006_auto_20200929_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 2, 18, 15, 7, 778465)),
        ),
    ]
