# Generated by Django 3.1.1 on 2020-10-14 19:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('currencies', '0011_auto_20201005_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='user',
            field=models.ForeignKey(blank=True, default='12486276-6a06-436f-b551-b2d21b279036', on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currency',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 14, 19, 30, 29, 601065)),
        ),
    ]
