# Generated by Django 3.1.1 on 2020-09-29 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_auto_20200929_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='purchase_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 29, 17, 56, 46, 610725)),
        ),
    ]
