# Generated by Django 3.1.1 on 2020-10-03 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_auto_20201002_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='expense',
            name='purchase_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 3, 18, 59, 38, 585870)),
        ),
    ]
