# Generated by Django 3.1.1 on 2020-10-05 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0012_auto_20201004_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='cost_conversion',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='purchase_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 5, 18, 15, 27, 308963)),
        ),
    ]
