# Generated by Django 3.1.2 on 2020-10-18 03:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0014_auto_20201014_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='purchase_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
