# Generated by Django 3.1.1 on 2020-10-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0015_auto_20201018_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
