# Generated by Django 3.1.1 on 2020-10-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0016_auto_20201021_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='expense',
            name='cost_conversion',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14),
        ),
    ]
