# Generated by Django 3.1.1 on 2020-09-21 18:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0006_auto_20200921_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('currency', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 21, 18, 33, 16, 591583))),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='trips.trip')),
            ],
        ),
    ]
