# Generated by Django 3.1.1 on 2020-09-21 18:43

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='id',
        ),
        migrations.AlterField(
            model_name='currency',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 21, 18, 43, 26, 840244)),
        ),
        migrations.AlterField(
            model_name='currency',
            name='currency_uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=uuid.uuid4, serialize=False),
        ),
    ]
