# Generated by Django 3.1.1 on 2020-09-29 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0005_auto_20200929_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 29, 17, 56, 46, 611451)),
        ),
    ]
