# Generated by Django 3.1.1 on 2020-10-02 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0007_auto_20201002_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 2, 19, 21, 54, 42078)),
        ),
    ]
