# Generated by Django 3.1.1 on 2020-10-03 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0008_auto_20201002_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 3, 18, 59, 38, 586959)),
        ),
    ]
