# Generated by Django 3.1.1 on 2020-10-04 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0009_auto_20201003_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 4, 20, 23, 0, 924432)),
        ),
    ]
