# Generated by Django 3.1.1 on 2020-10-05 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0010_auto_20201004_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 5, 18, 15, 27, 309661)),
        ),
    ]
