# Generated by Django 3.1.1 on 2020-09-16 02:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expense_uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('expense_type', models.CharField(max_length=20)),
                ('currency', models.CharField(max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=4)),
                ('purchase_date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 16, 2, 21, 45, 457463))),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trip')),
            ],
        ),
    ]
