# Generated by Django 3.1.1 on 2020-10-02 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_auto_20201002_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='home_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='expense',
            name='purchase_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 2, 19, 21, 54, 41380)),
        ),
    ]
