# Generated by Django 3.1.1 on 2020-10-14 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0013_auto_20201005_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='purchase_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 14, 19, 30, 29, 600293)),
        ),
    ]
