# Generated by Django 3.1.2 on 2020-10-25 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0020_auto_20201021_1932'),
        ('default_trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='default_trip',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_trips', to='trips.trip'),
        ),
    ]
