# Generated by Django 3.1.2 on 2020-10-25 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default_trips', '0002_auto_20201025_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='default_trip',
            old_name='trip',
            new_name='trip_uid',
        ),
    ]
