# Generated by Django 3.1.2 on 2020-11-05 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0020_auto_20201021_1932'),
        ('default_trips', '0003_auto_20201025_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='default_trip',
            name='trip_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trip'),
        ),
        migrations.AlterField(
            model_name='default_trip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_trips', to=settings.AUTH_USER_MODEL),
        ),
    ]
