# Generated by Django 3.1.1 on 2020-09-21 01:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=7)),
                ('length', models.IntegerField()),
                ('home_currency', models.CharField(max_length=3)),
                ('start_date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 21, 1, 56, 7, 178978))),
                ('end_date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 21, 1, 56, 7, 178995))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
