# Generated by Django 3.1.1 on 2020-09-16 02:21

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('home_currency', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 16, 2, 21, 45, 429210))),
            ],
        ),
    ]
